%define GAME_SEGMENT 0x100
%define STACK_BASE_ADDR 0xFF00
%define STACK_POINTER_ADDR 0xFFFF
%define FRUIT_CHAR '#'
%define SNAKE_BODY_CHAR '*'
%define SNAKE_HEAD_CHAR '@'
%define DIRECTION_LEFT 0x0
%define DIRECTION_UP 0x1
%define DIRECTION_RIGHT 0x2
%define DIRECTION_DOWN 0x3
%define RING_BUFFER_BASE 0x1038
%define RING_BUFFER_END 0x1042
;%define RING_BUFFER_END 0x10FE
%define MAX_RING_BUFFER_SIZE RING_BUFFER_END - RING_BUFFER_BASE
